# Generated by Django 5.1.5 on 2025-01-27 17:17

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
    ]
