# Generated by Django 5.1.5 on 2025-01-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_year',
            new_name='published_year',
        ),
    ]
